name: Android Build

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Fix Android SDK
        run: sudo chmod -R a+w /usr/local/lib/android/sdk

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew assemble

  apk:
    name: Generate APK
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Fix Android SDK
        run: sudo chmod -R a+w /usr/local/lib/android/sdk
      - name: Build debug APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
